[current]
daves_url = "https://davesredistricting.org/maps#viewmap::3a0dfe27-c577-49d1-866f-898f9ef8f637"
context_url = "https://www.seattle.gov/redistricting/how-to-participate"

[consultant1]
daves_url = "https://davesredistricting.org/join/043b88e8-c52b-456b-b56f-07620fbd56d3"
context_url = "https://www.seattle.gov/redistricting/how-to-participate"

[consultant2]
daves_url = "https://davesredistricting.org/join/07b3eabd-9561-4d5f-b21f-93ad7481bcf5"
context_url = "https://www.seattle.gov/redistricting/how-to-participate"

[consultant3]
daves_url = "https://davesredistricting.org/join/2074e36d-2729-437b-824d-4b86fd67eb4a"
context_url = "https://www.seattle.gov/redistricting/how-to-participate"

[consultant4]
daves_url = "https://davesredistricting.org/join/4b02b21a-0932-4778-b309-efa96fc7b5b3"
context_url = "https://www.seattle.gov/redistricting/how-to-participate"

[rjs]
daves_url = "https://davesredistricting.org/maps#viewmap::0d7334b5-2477-42ec-8862-8368c0eae824"
context_url = "https://www.redistrictingjusticewa.org/statements-blog/seattle-redistricting-commission-proposal-from-coalition"

[joanna_cullen_YTD3]
daves_url = "https://davesredistricting.org/maps#viewmap::7734acc1-19a7-49c4-b4f3-c31300d49407"
context_url = "https://www.seattle.gov/documents/Departments/Redistricting/Public%20Comments/Map%20Image%20PDF%27s/JoannaCullen_PublicComment.pdf"

[joanna_cullen_YTD2]
daves_url = "https://davesredistricting.org/maps#viewmap::bf59697f-02f9-4fd8-b862-4cc7abfe558c"
context_url = "https://www.seattle.gov/documents/Departments/Redistricting/Public%20Comments/Map%20Image%20PDF%27s/JoannaCullen_PublicComment.pdf"

[kathryn_keller_1]
daves_url = "https://davesredistricting.org/join/4f136ab9-bd33-4479-bec5-683f99fdf40b"
context_url = "https://www.seattle.gov/documents/Departments/Redistricting/Public%20Comments/Map%20Image%20PDF%27s/KathrynKeller_PublicComment.pdf"

[kathryn_keller_1_1]
daves_url = "https://davesredistricting.org/join/911cac2e-82bb-4ec7-9695-3da3b29b84e1"
context_url = "https://www.seattle.gov/documents/Departments/Redistricting/Public%20Comments/Map%20Image%20PDF%27s/KathrynKeller_PublicComment.pdf"

[kathryn_keller_1_2]
daves_url = "https://davesredistricting.org/join/4b843160-ccc9-4d0b-b42d-b2cfc07bad8b"
context_url = "https://www.seattle.gov/documents/Departments/Redistricting/Public%20Comments/Map%20Image%20PDF%27s/KathrynKeller_PublicComment.pdf"

[paul_chapman_1]
daves_url = "https://davesredistricting.org/maps#viewmap::ebc1eba7-4cbe-47a4-a98a-c4a5c215a5a3"
context_url = "https://www.seattle.gov/documents/Departments/Redistricting/Public%20Comments/Map%20Image%20PDF%27s/PaulChapman_PublicComment.pdf"

[paul_chapman_2]
daves_url = "https://davesredistricting.org/maps#viewmap::4d5800a2-cc90-4c80-8fef-beb5b2f4f550"
context_url = "https://www.seattle.gov/documents/Departments/Redistricting/Public%20Comments/Map%20Image%20PDF%27s/PaulChapman_PublicComment.pdf"

[paul_chapman_3]
daves_url = "https://davesredistricting.org/maps#viewmap::74a7b05f-7d43-446b-a7b0-b64de15e5458"
context_url = "https://www.seattle.gov/documents/Departments/Redistricting/Public%20Comments/Map%20Image%20PDF%27s/PaulChapman_PublicComment.pdf"

[paul_chapman_bottom]
daves_url = "https://davesredistricting.org/join/05a3d768-4c46-4bf1-a979-7e58e34828c1"
context_url = "https://www.seattle.gov/documents/Departments/Redistricting/Public%20Comments/Map%20Image%20PDF%27s/PaulChapman_PublicComment.pdf"
